<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Grammars\GlacierLexer.g4" />
    <None Remove="Grammars\GlacierParser.g4" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Grammars\GlacierLexer.g4" />
    <Antlr4 Include="Grammars\GlacierParser.g4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.100">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
